djangoProject7/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('',include('filesharing.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filesharing/urls.py
from django.urls import path
from .import views

app_name='filesharing'
urlpatterns = [
      path('home1',views.home1,name='home1'),
      path('allusers',views.allusers,name='allusers'),
      path('My_Files',views.My_Files,name='My_Files'),
      path('uploadfile',views.uploadfile,name='uploadfile'),
      path('<slug:user>',views.ousersfile,name='ousersfiles'),
      path('My_Files/<int:pk>',views.FileDelete.as_view(),name='delete'),
      path('My_Files/makeprivate/<int:pk>',views.makeprivate,name='makeprivate'),
      path('My_Files/makepublic/<int:pk>',views.makepublic,name='makepublic'),
      path('folder/<int:pk>/uploadlinkedfile',views.uploadlinkedfile,name='uploadlinkedfile'),
      path('o/<int:folder_id>/', views.insidefolders, name='detail'),
      path('folder_upload/<int:pk>/', views.FolderUpload, name='folder-upload'),
      path('folder_upload_index/', views.FolderUploadIndex, name='folder-upload-index'),
      path('folder/add/', views.nolinkfolder, name='folder-add'),
      path('folder/add/<int:pk>',views.Folder_Create,name='linked-folder-add'),
      path('folder/<int:folder_id>/', views.user_details, name='user-linked-files'),
      path('My_Folder/<int:pk>',views.FolderDelete.as_view(), name='folder-delete'),
      path('download_folder/<int:pk>/',views.download_folder,name='download_folder'),
      path('<int:pk>/',views.starredfile,name='starredfile'),
      path('remove/<int:pk>/',views.removestar,name='removestar'),
      path('stay/<int:pk>/',views.removestarstay,name='removestay'),
      path('starfolder/<int:pk>/',views.starredfolder,name='starredfolder'),
      path('folder/remove/<int:pk>/',views.removestarfolder,name='removestarfolder'),
      path('folder/stay/<int:pk>/',views.removestarstayfolder,name='removestayfolder'),

]

users/urls.py
from django.urls import path
from .import views


urlpatterns = [
      path('', views.home, name='home'),
      path('login',views.login,name='login'),
      path('register',views.register,name='register'),
      path('logout',views.logout,name='logout'),
      path('profile',views.profiles,name='profile'),
      path('profileupdate',views.profileupdate,name='profileupdate'),
      path('createdprofile',views.createdprofile,name='createdprofile'),
      path('alreadythere',views.alreadythere,name='alreadythere'),
      path('oprofile/<slug:user>', views.oprofile, name='oprofile')
]

filesharing/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import os
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)
# Create your models here.
class Folder(models.Model):
    name=models.CharField(max_length=100,null=True,blank=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE, default=None)
    linkedfolder=models.ForeignKey("self",null=True,on_delete=models.CASCADE,blank=True)

    def __str__(self):
        return  self.name

    def get_absolute_url(self):
        return reverse('fileshare:My_Files')

class File(models.Model):

    name = models.CharField(max_length=100,null=True,blank=True)
    file=models.FileField(upload_to=user_directory_path)
    created_on = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE, default=None)
    folder=models.ForeignKey(Folder,null=True,on_delete=models.CASCADE,blank=True)
    isprivate = models.BooleanField(default=False)

    def filename(self):
        return os.path.basename(self.file.name)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        file=File.objects.get(pk=self.pk)
        folders=file.folder
        if not folders :
            return reverse('filesharing:My_Files')
        else :
            return reverse('filesharing:user-linked-files',kwargs={'folder_id':folders.pk})

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)


class fav(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    sfile=models.ForeignKey(File,on_delete=models.CASCADE,default=None,null=True)
    sfolder=models.ForeignKey(Folder,on_delete=models.CASCADE,default=None,null=True)

    def __str__(self):
        if self.sfile:
            return str(self.sfile.id)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth import views as auth_views


# Create your models here.
class profile(models.Model):
    profilename = models.CharField(max_length=100)
    DOB = models.DateField()
    college = models.CharField(max_length=100)
    created = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='profilepic')
    owner=models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.profilename

filesharing/forms.py
from django import forms
from .models import File,Folder

class DocumentForm(forms.ModelForm):
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    class Meta:
        model = File
        fields = ('file', )


class FolderForm(forms.ModelForm):
    name=forms.CharField(max_length=100)
    class Meta:
        model = Folder
        fields = ['name']


class FolderUploadForm(forms.ModelForm):
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True, 'webkitdirectory': True, 'directory': True}))

    class Meta:
        model = Folder
        fields = ['file',]

users/forms.py
from django import forms
from .models import profile

class imageform(forms.ModelForm):

    class Meta:
        model = profile
        fields = ('image','profilename', )

class profilecreate(forms.ModelForm):

    class Meta:
        model = profile
        fields = ('image','profilename','DOB','college' )

filesharing/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect,reverse,get_object_or_404,HttpResponse
from django.urls import reverse_lazy
from django.contrib import messages

from .models import File,Folder,fav
from .forms import DocumentForm,FolderUploadForm,FolderForm
from django.views.generic.edit import FormView,DeleteView,UpdateView,CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
import zipfile
import os, io
from django.utils.text import slugify

def starredfile(request,pk):
    file=File.objects.get(pk=pk)
    user = file.user
    try:
        f=fav.objects.get(user=request.user,sfile_id=file.id)

    except fav.DoesNotExist:
        f = fav(user=request.user, sfile_id=file.id)
        f.save()
    folder=file.folder
    if not folder:
     if user==request.user:
        return redirect('filesharing:My_Files')
     else :
        return redirect('filesharing:ousersfiles',user)
    else:
     if user==request.user:
        return redirect('filesharing:user-linked-files',folder.pk)
     else :
        return redirect('filesharing:detail', folder.pk)
def starredfolder(request,pk):

    folder = Folder.objects.get(pk=pk)
    user1 = folder.user
    try:
        f = fav.objects.get(user=request.user, sfolder_id=folder.id)

    except fav.DoesNotExist:
        f = fav(user=request.user, sfolder_id=folder.id)
        f.save()

    linkfolder = folder.linkedfolder

    f.save()

    if not linkfolder:
         if user1==request.user:
           return redirect('filesharing:My_Files')
         else :
           return redirect('filesharing:ousersfiles',user1)
    else:
        if user1==request.user:
         return redirect('filesharing:user-linked-files',linkfolder.pk)
        else :
         return redirect('filesharing:detail', linkfolder.pk)
def removestar(request,pk):
    file = File.objects.get(pk=pk)
    f=fav.objects.filter(user=request.user,sfile=file.id)
    f.delete()
    return redirect('filesharing:home1')
def removestarfolder(request,pk):
    folder = Folder.objects.get(pk=pk)
    f = fav.objects.filter(user=request.user, sfolder=folder.id)
    f.delete()
    return redirect('filesharing:home1')
def removestarstay(request,pk):
    file = File.objects.get(pk=pk)
    folder=file.folder
    user=file.user
    f = fav.objects.filter(user=request.user, sfile=file.id)
    f.delete()
    if not folder:
         if user==request.user:
           return redirect('filesharing:My_Files')
         else :
           return redirect('filesharing:ousersfiles',folder.user)
    else:
        if user==request.user:
         return redirect('filesharing:user-linked-files',folder.pk)
        else :
         return redirect('filesharing:detail', folder.pk)
def removestarstayfolder(request,pk):
    f = Folder.objects.get(pk=pk)
    folder = f.linkedfolder
    user=f.user
    foli = fav.objects.filter(user=request.user, sfolder=f.id)
    foli.delete()
    if not folder:
         if user==request.user:
           return redirect('filesharing:My_Files')
         else :
           return redirect('filesharing:ousersfiles',user)
    else:
        if user==request.user:
         return redirect('filesharing:user-linked-files',folder.pk)
        else :
         return redirect('filesharing:detail', folder.pk)
def user_details(request,folder_id):
    f = fav.objects.filter(user=request.user)
    files = f

    fi = set(())
    fold = set(())
    for i in range(len(files)):
        if files[i].sfile:
            fi.add(files[i].sfile.id)
        elif files[i].sfolder:
            fold.add(files[i].sfolder.id)


    folder = get_object_or_404(Folder,pk=folder_id)
    files = folder.file_set.all()
    folders = folder.folder_set.all()
    print(files,folders)
    favfiles=[]
    notfavfiles=[]
    favfolders=[]
    notfavfolders=[]
    for i in range(len(files)):
        if files[i].id in fi :
            favfiles.append(files[i])
        else:
             notfavfiles.append(files[i])
    for i in range(len(folders)):
        if folders[i].id in fold :
            favfolders.append(folders[i])
        else:
             notfavfolders.append(folders[i])


    temp = folder
    parent_list = []
    parent_list.append(temp)
    while temp.linkedfolder:
        parent = temp.linkedfolder
        parent_list.append(parent)
        temp = parent
    active_folder = parent_list[0]
    parent_list.reverse()
    print(notfavfiles,favfiles)
    context={'folder':folder,'folders':favfolders,'notfavfolders':notfavfolders,'files':favfiles,'notfav':notfavfiles,'folder_id':folder_id,'parent_list':parent_list,'active_folder':active_folder}
    return render(request,'filesharing/user_linkedfiles.html',context)


def insidefolders(request,folder_id):
    f = fav.objects.filter(user=request.user)
    files = f

    fi = set(())
    fold = set(())
    for i in range(len(files)):
        if files[i].sfile:
            fi.add(files[i].sfile.id)
        elif files[i].sfolder:
            fold.add(files[i].sfolder.id)

    folder = get_object_or_404(Folder, pk=folder_id)
    files2= folder.file_set.all()
    files=files2.filter(isprivate=False)
    folders = folder.folder_set.all()
    favfiles = []
    notfavfiles = []
    favfolders = []
    notfavfolders = []
    for i in range(len(files)):
        if files[i].id in fi :
            favfiles.append(files[i])
        else:
             notfavfiles.append(files[i])
    for i in range(len(folders)):
        if folders[i].id in fold:
            favfolders.append(folders[i])
        else:
            notfavfolders.append(folders[i])
    user=folder.user
    temp=folder
    parent_list=[]
    parent_list.append(temp)
    while temp.linkedfolder:
         parent=temp.linkedfolder
         parent_list.append(parent)
         temp=parent
    active_f=parent_list[0]
    parent_list.reverse()
    context = {'folder': folder, 'folders': favfolders,'notfavfolders':notfavfolders, 'files': favfiles,'notfav':notfavfiles, 'folder_id': folder_id, 'parent_list': parent_list,
                'active_folder': active_f,'user':user}
    return render(request, 'filesharing/details.html', context)


def home1(request):

    try:
     f=fav.objects.filter(user=request.user)
     files=f

     fi=[]
     fold=[]
     for i in range(len(files)):
        if  files[i].sfile :
         fi.append(files[i].sfile.id)
        elif files[i].sfolder :
          fold.append(files[i].sfolder.id)
     fo=[]
     folder=[]
     for i in range(len(fi)):
         fo.append(File.objects.get(pk=fi[i]))
     for i in range(len(fold)):
         folder.append(Folder.objects.get(pk=fold[i]))

     ofo=[]
     ufo=[]

     for i in range(len(folder)):
         temp=folder[i]
         if  temp.user==request.user:
             ufo.append(folder[i])
         else:
              ofo.append(folder[i])

     context = {'folders': ofo,'files':fo,'ufolders':ufo}
    except File.DoesNotExist and Folder.DoesNotExist:
     files=None
     folders=None
    return render(request, 'filesharing/home1.html', context)
def allusers(request):
    all_users = User.objects.all()
    current_user = request.user
    return render(request, 'filesharing/users.html', {'all_users': all_users, 'current_user': current_user})
def My_Files(request):
    user = request.user
    all_files = File.objects.filter(user=user)
    all_folders = Folder.objects.filter(user=user)
    top_folder = all_folders.filter(linkedfolder__isnull=True)
    top_file = all_files.filter(folder__isnull=True)
    f = fav.objects.filter(user=request.user)
    files = f

    fi = set(())
    fold = set(())
    for i in range(len(files)):
        if files[i].sfile:
            fi.add(files[i].sfile.id)
        elif files[i].sfolder:
            fold.add(files[i].sfolder.id)

    favfiles = []
    notfavfiles = []
    favfolders = []
    notfavfolders = []
    for i in range(len(top_file)):
        if top_file[i].id in fi:
            favfiles.append(top_file[i])
        else:
            notfavfiles.append(top_file[i])
    for i in range(len(top_folder)):
        if top_folder[i].id in fold:
            favfolders.append(top_folder[i])
        else:
            notfavfolders.append(top_folder[i])
    context = {'all_files': favfiles, 'notfav':notfavfiles,'all_folders': favfolders,'notfavfolders':notfavfolders}

    return render(request, 'filesharing/MY_Files.html', context)
def uploadfile(request):
    if request.method =='POST':

            form = DocumentForm(request.POST, request.FILES)

            if form.is_valid():
                for field in request.FILES.keys():
                    for formfile in request.FILES.getlist(field):
                        f = File(file=formfile, user=request.user)
                        f.name = f.filename()
                        f.save()
                return redirect('filesharing:My_Files')
            else:
                return render(request, 'filesharing/uploadfile.html', {'form': form})
    else:
            form = DocumentForm(None)
            return render(request, 'filesharing/uploadfile.html', {'form': form})
def uploadlinkedfile(request,pk):
    if request.method == 'POST':

        form = DocumentForm(request.POST, request.FILES)

        if form.is_valid():
            for field in request.FILES.keys():
                for formfile in request.FILES.getlist(field):
                    f = File(file=formfile, user=request.user)
                    f.name = f.filename()
                    f.folder=Folder.objects.get(pk=pk)
                    f.save()
                    return redirect('filesharing:user-linked-files', pk)
        else:
            return render(request, 'filesharing/uploadfile.html', {'form': form})
    else:
        form = DocumentForm(None)
        return render(request, 'filesharing/uploadfile.html', {'form': form})
class FileDelete(DeleteView):
    model = File

    def get_success_url(self):
        f = File.objects.get(pk=self.kwargs['pk'])
        folder = f.folder

templates/filesharing/linkedfolderupload.html
{% extends 'filesharing/base.html'%}

{% block title%} Add Folder {% endblock %}

{% block body %}
<div class="card-body" style="background-color:white">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div style="display:none">
      <input type="text" id="path" name="path">
    </div>
    <p><label for="id_file">File:   </label>
    <input id="id_file" type="file" name="file" multiple webkitdirectory="" onchange="myFunction()" required /></p>
    <button type="submit" class="btn btn-success">Submit</button>

  </form>
</div>


<script>
  function myFunction(){
    var x = document.getElementById("path");
    var y = document.getElementById("id_file");
    var txt = "";
    if ('files' in y) {
      for (var i = 0; i < y.files.length; i++) {
        var file = y.files[i];
        if ('webkitRelativePath' in file) {
          txt = txt + file.webkitRelativePath + " ";
        }
      }
    }
    x.value = txt
  }
</script>

{% endblock %}

templates/filesharing/multiplefiles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="card-body" style="background-color:white">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div style="display:none">
      <input type="text" id="path" name="path">
    </div>
    <p><label for="id_file">File:   </label>
    <input id="id_file" type="file" name="file" multiple webkitdirectory="" onchange="myFunction()" required /></p>
    <button type="submit" class="btn btn-success">Submit</button>

  </form>
</div>
<script>
  function myFunction(){
    var x = document.getElementById("path");
    var y = document.getElementById("id_file");
    var txt = "";
    if ('files' in y) {
      for (var i = 0; i < y.files.length; i++) {
        var file = y.files[i];
        if ('webkitRelativePath' in file) {
          txt = txt + file.webkitRelativePath + ",";
        }
      }
    }
    x.value = txt
  }
</script>
</body>
</html>

templates/filesharing/user_linkedfiles.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

  <head>
    <meta charset="utf-8">
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="{%  static "css/styles.css" %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
 <style>
      .dropbtn {
       margin-left: 1350px;
  background-color: #5897fb ;
  color: white;
          width: 150px;
  padding-bottom: 15px;
  font-size: 20px;
          text-align:center;
  border: none;
}
      .dropdown {
  position: relative;
  display: inline-block;
}
.dropdown-content {
    margin-left: 1350px;
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}
.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}
.dropdown-content a:hover {background-color: #ddd;}
.dropdown:hover .dropdown-content {display: block;}
.dropdown:hover .dropbtn {background-color: #3e8e41;}



     </style>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

</head>
  <body>



<div class="sidebar">
  <a href="{% url 'filesharing:home1' %}"><i class="fa fa-fw fa-home"></i> Home</a>
  <a  class="active" href="{% url 'filesharing:My_Files' %}"><i class="fa fa-fw fa-file"></i>My files</a>
  <a  href="{% url 'filesharing:allusers' %}"><i class="fa fa-fw fa-user"></i>All Users</a>
  <a href="{% url 'createdprofile' %}"><i class="fa fa-fw fa-address-card"></i>MY Profile</a>
  <a href="{% url 'logout' %}"><i class="fa fa-fw fa"></i>Logout</a>
</div>
<div class="dropdown">
  <button class="dropbtn">Edit </button>
  <div class="dropdown-content">
    <a href="{% url 'filesharing:linked-folder-add' folder_id %}">create folder</a><br>
    <a href="{% url 'filesharing:folder-upload' active_folder.id %}">Upload folder</a><br>

    <a id="button1" type="submit">Add File</a>


  </div>
</div>



<script>

    var dropdown = document.getElementsByClassName("dropbtn");
var i;

for (i = 0; i < dropdown.length; i++) {
  dropdown[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var dropdownContent = this.nextElementSibling;
    if (dropdownContent.style.display === "block") {
      dropdownContent.style.display = "none";
    } else {
      dropdownContent.style.display = "block";
    }
  });
}



</script>

<div class="content">
 <ol class="breadcrumb">
  <li class="breadcrumb-item"> <a href="{% url 'filesharing:My_Files' %}"> {{ user.username }} </a> </li>
  {% for parent in parent_list %}
    {% if parent is not active_folder %}
      <li class="breadcrumb-item"> <a href="{% url 'filesharing:user-linked-files' parent.id %}"> {{ parent }}</a> </li>
    {% else %}
    <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'filesharing:user-linked-files' parent.id %}" style="color:black"> {{ parent }}</a></li>
    {% endif %}
  {% endfor %}
</ol>

  {%  if notfav or files  %}
  <h2> Files</h2>
  {% endif %}
<div class="list-group">
     </div>
{% for file in notfav %}
        <div class="list-group">
             <div class="list-group-item">
                 <h4 class="list-group-item-text">{{ file.name}}</h4>
                  <p class="list-group-item-text">{{ file.created_on}}</p>
                <td> <a class="list-group-item-text" href="{{ file.file.url }}" target="_blank"><button type="button" class="btn btn-primary">Preview</button> </a> </td>

                 <a class="list-group-item-text" href="{{ file.file.url }}" target="_blank" download><button type="button" class="btn btn-primary">Download</button></a>
               <a class="list-group-item-text" href="{% url 'filesharing:delete' file.pk %}" ><button type="button" class="btn btn-primary">Delete</button></a>
                 <a class="list-group-item-text" href="{% url 'filesharing:starredfile' file.pk  %}" ><button type="button" class="btn btn-primary">Add to Favourites</button></a>

                 {% if file.isprivate %}
                    <a class="list-group-item-text" href="{% url 'filesharing:makepublic' file.pk %}" ><button type="button" class="btn btn-primary">Make Public</button></a>

                 {% else %}
                     <a class="list-group-item-text" href="{% url 'filesharing:makeprivate' file.pk %}" ><button type="button" class="btn btn-primary">Make Private</button></a>
                  {% endif %}

             </div>
        </div>
 {% endfor %}




<div class="list-group">
      {% for file in files %}
            <div class="list-group">
                 <div class="list-group-item">
                     <h4 class="list-group-item-text">{{ file.name}}</h4>
                      <p class="list-group-item-text">{{ file.created_on}}</p>
                      <a class="list-group-item-text" href="{{ file.file.url }}" target="_blank"><button type="button" class="btn btn-primary">Preview</button> </a> </td>
                      <a class="list-group-item-text" href="{{ file.file.url }}" target="_blank" download><button type="button" class="btn btn-primary">Download</button></a>
                      <a class="list-group-item-text" href="{% url 'filesharing:delete' file.pk %}" ><button type="button" class="btn btn-primary">Delete</button></a>

                           <a class="list-group-item-text" href="{% url 'filesharing:removestay' file.pk %}" ><button type="button" class="btn btn-primary">Remove From Favourites</button></a>

                     {% if file.isprivate %}
                        <a class="list-group-item-text" href="{% url 'filesharing:makepublic' file.pk %}" ><button type="button" class="btn btn-primary">Make Public</button></a>
                      {% else %}
                         <a class="list-group-item-text" href="{% url 'filesharing:makeprivate' file.pk %}" ><button type="button" class="btn btn-primary">Make Private</button></a>
                      {% endif %}
                </div>
            </div>
      {% endfor %}
    </div>

<div class="list-group">
 {% if folders or notfavfolders %}
 <h2> Folders</h2>
{% endif %}

{% for f in folders %}
        <div class="list-group">
             <div class="list-group-item">
                   <i class="material-icons"  style="color: orange" >
              folder
                 </i>
                 <a style="font-size:25px;color:black"  href="{% url 'filesharing:user-linked-files' f.id %}" > {{ f }} </a> <br>
                 <p>  </p>
                   <a  class="list-group-item-text" href="{% url 'filesharing:folder-delete' f.id %}" ><button type="button" class="btn btn-primary">Delete</button></a>
                       <a class="list-group-item-text" href="{% url 'filesharing:download_folder' f.id %}" target="_blank" download><button type="button" class="btn btn-primary">Download</button></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  <a class="list-group-item-text" href="{% url 'filesharing:removestayfolder' f.id %}" ><button type="button" class="btn btn-primary">Remove From Favourites</button></a>



          </div>
        </div>
 {% endfor %}

{% for f in notfavfolders %}
        <div class="list-group">
             <div class="list-group-item">
                   <i class="material-icons"  style="color: orange" >
              folder
                 </i>
 <a style="font-size:25px;color:black"  href="{% url 'filesharing:user-linked-files' f.id %}" > {{ f }} </a> <br>
                 <p>  </p>                   <a  href="{% url 'filesharing:folder-delete' f.id %}" ><button type="button" class="btn btn-primary">Delete</button></a>
                       <a class="list-group-item-text" href="{% url 'filesharing:download_folder' f.id %}" target="_blank" download><button type="button" class="btn btn-primary">Download</button></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                 <a class="list-group-item-text" href="{% url 'filesharing:starredfolder' f.id %}" ><button type="button" class="btn btn-primary"> Add to  Favourites</button></a>



          </div>
        </div>
 {% endfor %}

 </div>






   <script>
     var el= document.getElementById('button1')
         if(el)
         {
             el.addEventListener('click',function(){
             document.querySelector('.bg-modal').style.display='flex';
            });

         }
   </script>



  <div class="bg-modal">
    <div class="modal-content">
        <div class="close">+</div>
           <form action='uploadlinkedfile' method="POST"  enctype="multipart/form-data">
             {% csrf_token %}
               <input type="file" name="file" >
             <button type="submit">Upload</button>
           </form>


    </div>
  </div>
  <script>
      var el = document.querySelector('.close')
         if(el) {
             el.addEventListener('click', function () {
                 document.querySelector('.bg-modal').style.display = 'none';
             });

         }
  </script>
</div>
  </body>
</html>